--
-- ER/Studio 8.0 SQL Code Generation
-- Company :      USAC
-- Project :      Practica4.dm1
-- Author :       USER
--
-- Date Created : Friday, April 24, 2015 22:07:15
-- Target DBMS : MySQL 5.x
--

-- 
-- TABLE: ASIGN_BUS 
--

CREATE TABLE ASIGN_BUS(
    BUS     INT    NOT NULL,
    RUTA    INT    NOT NULL,
    PRIMARY KEY (BUS, RUTA)
)ENGINE=MYISAM
;



-- 
-- TABLE: ASIGN_RUTA 
--

CREATE TABLE ASIGN_RUTA(
    RUTA      INT    NOT NULL,
    PARADA    INT    NOT NULL,
    ORDEN     INT,
    PRIMARY KEY (RUTA, PARADA)
)ENGINE=MYISAM
;



-- 
-- TABLE: ASIGN_VIAJE 
--

CREATE TABLE ASIGN_VIAJE(
    PARADA    INT    NOT NULL,
    VIAJE     INT    NOT NULL,
    PRIMARY KEY (PARADA, VIAJE)
)ENGINE=MYISAM
;



-- 
-- TABLE: BUS 
--

CREATE TABLE BUS(
    BUS          INT               NOT NULL AUTO_INCREMENT,
    NOMBRE       VARCHAR(25)       NOT NULL,
    PRECIO_KM    DECIMAL(10, 0),
    CLASE_BUS    INT               NOT NULL,
    PRIMARY KEY (BUS)
)ENGINE=MYISAM
;



-- 
-- TABLE: CLASE_BUS 
--

CREATE TABLE CLASE_BUS(
    CLASE_BUS     INT            NOT NULL AUTO_INCREMENT,
    NOMBRE        VARCHAR(25),
    NO_ASIENTO    INT,
    PRIMARY KEY (CLASE_BUS)
)ENGINE=MYISAM
;



-- 
-- TABLE: CLIENTE 
--

CREATE TABLE CLIENTE(
    CLIENTE       INT            NOT NULL AUTO_INCREMENT,
    NOMBRE        VARCHAR(25),
    NACIMIENTO    DATE,
    PRIMARY KEY (CLIENTE)
)ENGINE=MYISAM
;



-- 
-- TABLE: FACTURA 
--

CREATE TABLE FACTURA(
    CLIENTE    INT               NOT NULL,
    FACTURA    INT               NOT NULL AUTO_INCREMENT,
    TOTAL      DECIMAL(10, 0),
    PRIMARY KEY (FACTURA)
)ENGINE=MYISAM
;



-- 
-- TABLE: PARADA 
--

CREATE TABLE PARADA(
    PARADA          INT    NOT NULL AUTO_INCREMENT,
    LOCALIZACION    INT,
    PRIMARY KEY (PARADA)
)ENGINE=MYISAM
;



-- 
-- TABLE: RUTA 
--

CREATE TABLE RUTA(
    RUTA           INT             NOT NULL AUTO_INCREMENT,
    DESCRIPCION    VARCHAR(150),
    NOMBRE         VARCHAR(25),
    PRIMARY KEY (RUTA)
)ENGINE=MYISAM
;



-- 
-- TABLE: TICKET 
--

CREATE TABLE TICKET(
    TICKET         INT               NOT NULL AUTO_INCREMENT,
    PRECIO         DECIMAL(10, 0),
    FACTURA        INT               NOT NULL,
    DESCRIPCION    VARCHAR(150),
    VIAJE          INT               NOT NULL,
    PRIMARY KEY (TICKET)
)ENGINE=MYISAM
;



-- 
-- TABLE: VIAJE 
--

CREATE TABLE VIAJE(
    VIAJE      INT            NOT NULL AUTO_INCREMENT,
    NOMBRE     VARCHAR(25)    NOT NULL,
    ESTADO     VARCHAR(25),
    RUTA       INT            NOT NULL,
    INICIO     INT            NOT NULL,
    FIN        INT            NOT NULL,
    CLIENTE    INT            NOT NULL,
    PRIMARY KEY (VIAJE)
)ENGINE=MYISAM
;



-- 
-- TABLE: ASIGN_BUS 
--

ALTER TABLE ASIGN_BUS ADD CONSTRAINT RefBUS2 
    FOREIGN KEY (BUS)
    REFERENCES BUS(BUS)
;

ALTER TABLE ASIGN_BUS ADD CONSTRAINT RefRUTA3 
    FOREIGN KEY (RUTA)
    REFERENCES RUTA(RUTA)
;


-- 
-- TABLE: ASIGN_RUTA 
--

ALTER TABLE ASIGN_RUTA ADD CONSTRAINT RefRUTA8 
    FOREIGN KEY (RUTA)
    REFERENCES RUTA(RUTA)
;

ALTER TABLE ASIGN_RUTA ADD CONSTRAINT RefPARADA9 
    FOREIGN KEY (PARADA)
    REFERENCES PARADA(PARADA)
;


-- 
-- TABLE: ASIGN_VIAJE 
--

ALTER TABLE ASIGN_VIAJE ADD CONSTRAINT RefPARADA13 
    FOREIGN KEY (PARADA)
    REFERENCES PARADA(PARADA)
;

ALTER TABLE ASIGN_VIAJE ADD CONSTRAINT RefVIAJE14 
    FOREIGN KEY (VIAJE)
    REFERENCES VIAJE(VIAJE)
;


-- 
-- TABLE: BUS 
--

ALTER TABLE BUS ADD CONSTRAINT RefCLASE_BUS1 
    FOREIGN KEY (CLASE_BUS)
    REFERENCES CLASE_BUS(CLASE_BUS)
;


-- 
-- TABLE: FACTURA 
--

ALTER TABLE FACTURA ADD CONSTRAINT RefCLIENTE17 
    FOREIGN KEY (CLIENTE)
    REFERENCES CLIENTE(CLIENTE)
;


-- 
-- TABLE: TICKET 
--

ALTER TABLE TICKET ADD CONSTRAINT RefVIAJE15 
    FOREIGN KEY (VIAJE)
    REFERENCES VIAJE(VIAJE)
;

ALTER TABLE TICKET ADD CONSTRAINT RefFACTURA22 
    FOREIGN KEY (FACTURA)
    REFERENCES FACTURA(FACTURA)
;


-- 
-- TABLE: VIAJE 
--

ALTER TABLE VIAJE ADD CONSTRAINT RefASIGN_RUTA20 
    FOREIGN KEY (RUTA, INICIO)
    REFERENCES ASIGN_RUTA(RUTA, PARADA)
;

ALTER TABLE VIAJE ADD CONSTRAINT RefASIGN_RUTA21 
    FOREIGN KEY (RUTA, FIN)
    REFERENCES ASIGN_RUTA(RUTA, PARADA)
;

ALTER TABLE VIAJE ADD CONSTRAINT RefCLIENTE28 
    FOREIGN KEY (CLIENTE)
    REFERENCES CLIENTE(CLIENTE)
;


